<?php

namespace DoctrineORMModule\Proxy\__CG__\KJ\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class BJobcagtegory extends \KJ\Entity\BJobcagtegory implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getJcatId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["jcatId"];
        }
        $this->__load();
        return parent::getJcatId();
    }

    public function addSub(\KJ\Entity\BSubject $sub)
    {
        $this->__load();
        return parent::addSub($sub);
    }

    public function removeSub(\KJ\Entity\BSubject $sub)
    {
        $this->__load();
        return parent::removeSub($sub);
    }

    public function getSub()
    {
        $this->__load();
        return parent::getSub();
    }

    public function setCom(\KJ\Entity\ACompany $com = NULL)
    {
        $this->__load();
        return parent::setCom($com);
    }

    public function getCom()
    {
        $this->__load();
        return parent::getCom();
    }

    public function setCat(\KJ\Entity\BCategory $cat = NULL)
    {
        $this->__load();
        return parent::setCat($cat);
    }

    public function getCat()
    {
        $this->__load();
        return parent::getCat();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'jcatId', 'sub', 'com', 'cat');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}