<?php

namespace DoctrineORMModule\Proxy\__CG__\KJ\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class ACompany extends \KJ\Entity\ACompany implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getComId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["comId"];
        }
        $this->__load();
        return parent::getComId();
    }

    public function setUserId($userId)
    {
        $this->__load();
        return parent::setUserId($userId);
    }

    public function getUserId()
    {
        $this->__load();
        return parent::getUserId();
    }

    public function setApprove($approve)
    {
        $this->__load();
        return parent::setApprove($approve);
    }

    public function getApprove()
    {
        $this->__load();
        return parent::getApprove();
    }

    public function setComName($comName)
    {
        $this->__load();
        return parent::setComName($comName);
    }

    public function getComName()
    {
        $this->__load();
        return parent::getComName();
    }

    public function setComLocation($comLocation)
    {
        $this->__load();
        return parent::setComLocation($comLocation);
    }

    public function getComLocation()
    {
        $this->__load();
        return parent::getComLocation();
    }

    public function setComPhone($comPhone)
    {
        $this->__load();
        return parent::setComPhone($comPhone);
    }

    public function getComPhone()
    {
        $this->__load();
        return parent::getComPhone();
    }

    public function setComEmail($comEmail)
    {
        $this->__load();
        return parent::setComEmail($comEmail);
    }

    public function getComEmail()
    {
        $this->__load();
        return parent::getComEmail();
    }

    public function setComWeb($comWeb)
    {
        $this->__load();
        return parent::setComWeb($comWeb);
    }

    public function getComWeb()
    {
        $this->__load();
        return parent::getComWeb();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'comId', 'userId', 'approve', 'comName', 'comLocation', 'comPhone', 'comEmail', 'comWeb');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}