<!doctype html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7]> <html class="no-js ie6 oldie" lang="en"> <![endif]-->
<!--[if IE 7]>    <html class="no-js ie7 oldie" lang="en"> <![endif]-->
<!--[if IE 8]>    <html class="no-js ie8 oldie" lang="en"> <![endif]-->
<!--[if gt IE 8]><! --> 
<html class="no-js" lang="en"> <!--<![endif]-->
	<head>
		<meta charset="utf-8" />
		<!-- Always force latest IE rendering engine (even in intranet) & Chrome Frame -->
		<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
		<!-- Mobile viewport optimized: h5bp.com/viewport -->
		<meta name="viewport" content="width=device-width">

		<title>BootMetro</title>

		<meta name="robots" content="index, nofollow">
		<meta name="description" content="MetroUI-Web : Simple and complete web UI framework to create web apps with Windows 8 Metro user interface." />
		<meta name="keywords" content="metro, metroui, metro-ui, metro ui, windows 8, metro style, bootstrap, framework, web framework, css, html" />
		<meta name="author" content="AozoraLabs by Marcello Palmitessa"/>

		<!-- remove or comment this line if you want to use the local fonts -->
		<!--<link href='http://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700' rel='stylesheet' type='text/css'>-->

		<link rel="stylesheet" type="text/css" href="/bootmetro/content/css/bootstrap.css">
		<link rel="stylesheet" type="text/css" href="/bootmetro/content/css/bootstrap-responsive.css">
		<link rel="stylesheet" type="text/css" href="/bootmetro/content/css/bootmetro.css">
		<link rel="stylesheet" type="text/css" href="/bootmetro/content/css/bootmetro-tiles.css">
		<link rel="stylesheet" type="text/css" href="/bootmetro/content/css/bootmetro-charms.css">
		<link rel="stylesheet" type="text/css" href="/bootmetro/content/css/metro-ui-light.css">
		<link rel="stylesheet" type="text/css" href="/bootmetro/content/css/icomoon.css">
		<link rel="stylesheet" type="text/css" href="/datepicker/css/datepicker.css">

		<!--  these two css are to use only for documentation -->
		<link rel="stylesheet" type="text/css" href="/bootmetro/content/css/demo.css">
		<link rel="stylesheet" type="text/css" href="/bootmetro/scripts/google-code-prettify/prettify.css" >

		<!-- fav and touch icons -->
		<link rel="shortcut icon" href="/bootmetro/content/ico/favicon.ico">
		<link rel="apple-touch-icon-precomposed" sizes="144x144" href="/bootmetro/content/ico/apple-touch-icon-144-precomposed.png">
		<link rel="apple-touch-icon-precomposed" sizes="114x114" href="/bootmetro/content/ico/apple-touch-icon-114-precomposed.png">
		<link rel="apple-touch-icon-precomposed" sizes="72x72" href="/bootmetro/content/ico/apple-touch-icon-72-precomposed.png">
		<link rel="apple-touch-icon-precomposed" href="/bootmetro/content/ico/apple-touch-icon-57-precomposed.png">

		<!-- All JavaScript at the bottom, except for Modernizr and Respond. Modernizr enables HTML5 elements & feature detects; Respond is a polyfill for min/max-width CSS3 Media Queries For optimal performance, use a custom Modernizr build: www.modernizr.com/download/ -->
		<script src="/bootmetro/scripts/modernizr-2.6.1.min.js"></script>
	</head>

	<body data-accent="blue">

		<header id="nav-bar" class="container-fluid">
			<div class="row-fluid">
				<div class="span8">
					<div id="header-container">
						<a id="backbutton" class="win-backbutton" href="./index.html"></a>
						<h5>BootMetro</h5>
						<div class="dropdown">
							<a class="header-dropdown dropdown-toggle accent-color" data-toggle="dropdown" href="#">
								Menu
								<b class="caret"></b>
							</a>
							<ul class="dropdown-menu">
								<li><a href="./hub.html">Hub</a></li>
								<li><a href="./tiles-templates.html">Tile Templates</a></li>
								<li><a href="./listviews.html">ListViews</a></li>
								<li><a href="./appbar-demo.html">Demo App-Bar</a></li>
								<li><a href="./table.html">Demo Table</a></li>
								<li><a href="./icons.html">Icons</a></li>
								<li><a href="./scaffolding.html">Bootstrap Scaffolding</a></li>
								<li><a href="./base-css.html">Bootstrap Base CSS</a></li>
								<li><a href="./components.html">Bootstrap Components</a></li>
								<li><a href="./javascript.html">Bootstrap Javascript</a></li>
								<li class="divider"></li>
								<li><a href="./index.html">Home</a></li>
							</ul>
						</div>
					</div>
				</div>
				<div id="top-info" class="pull-right">
					<a href="#" class="pull-left">
						<div class="top-info-block">
							<h3>FirstName</h3>
							<h4>LastName</h4>
						</div>
						<div class="top-info-block">
							<b class="icon-user"></b>
						</div>
					</a>
					<hr class="separator pull-left"/>
					<a id="settings" class="pull-left" href="#">
						<b class="icon-settings"></b>
					</a>
				</div>
			</div>
		</header>

		<div class="container-fluid">
			<div class="row-fluid">
				<?php echo $this->content; ?>
			</div>
		</div>

		<div id="charms" class="win-ui-dark">

			<div id="theme-charms-section" class="charms-section">
				<div class="charms-header">
					<a href="#" class="close-charms win-command">
						<span class="win-commandimage win-commandring">&#xe05d;</span>
					</a>
					<h2>Settings</h2>
				</div>

				<div class="row-fluid">
					<div class="span12">

						<form class="">
							<label for="win-theme-select">Change theme:</label>
							<select id="win-theme-select" class="">
								<option value="metro-ui-semilight">Semi-Light</option>
								<option value="metro-ui-light">Light</option>
								<option value="metro-ui-dark">Dark</option>
							</select>
						</form>

					</div>
				</div>
			</div>

		</div>
		
		<script type="text/javascript" src='/bootmetro/scripts/jquery-1.8.2.min.js'></script>
		<script type="text/javascript" src="/bootmetro/scripts/google-code-prettify/prettify.js"></script>
		<script type="text/javascript" src="/bootmetro/scripts/jquery.mousewheel.js"></script>
		<script type="text/javascript" src="/bootmetro/scripts/jquery.scrollTo.js"></script>
		<script type="text/javascript" src="/bootmetro/scripts/bootstrap.min.js"></script>
		<script type="text/javascript" src="/bootmetro/scripts/bootmetro.js"></script>
		<script type="text/javascript" src="/bootmetro/scripts/bootmetro-charms.js"></script>
		<script type="text/javascript" src="/bootmetro/scripts/demo.js"></script>
		<script type="text/javascript" src="/bootmetro/scripts/holder.js"></script>
		<script type="text/javascript" src="/datepicker/js/bootstrap-datepicker.js"></script>
		<script type="text/javascript" src="/js/custom-script.js"></script>
		
		<script type="text/javascript">$(".metro").metro();</script>
		
	</body>
</html>
