<form class="form-horizontal" method="post" action="<?php echo $this->url('home/action', array('action' => 'UpdateCompany')) ?>">   
    <fieldset>
               
        <div class="control-group">
            <label class="control-label" for="inputEmail"></label>
            <div class="controls">  
                <input type="hidden" name="com_id" value="<?php echo $com->getComId(); ?>" />
            </div>
        </div>
            
        <div class="control-group">
            <label class="control-label" for="inputEmail">Company name :</label>
            <div class="controls">  
                <input type="text" name ="com_name" value="<?php echo $com->getComName()?> "> 
            </div>
        </div>
            
        <div class="control-group">
            <label class="control-label" for="inputEmail">Location :</label>
            <div class="controls">  
                <input type="text" name="com_location" value=" <?php echo $com->getComLocation() ?> ">
            </div>
        </div>
            
        <div class="control-group">
            <label class="control-label" for="inputEmail">Tel :</label>
            <div class="controls">  
                <input type="text" name ="com_phone" value="<?php echo $com->getComPhone(); ?>"> 
            </div>
        </div>
            
        <div class="control-group">
            <label class="control-label" for="inputEmail">Email :</label>
            <div class="controls">  
                <input type="text" name ="com_email" value="<?php echo $com->getComEmail(); ?>"> 
            </div>
        </div>
            
        <div class="control-group">
            <label class="control-label" for="inputEmail">Web site :</label>
                <div class="controls">  
                    <input type="text" name ="com_web" value="<?php echo $com->getComWeb(); ?>">
                </div>
        </div>
            
        <div class="control-group">
            <label class="control-label" for="inputEmail"></label>
            <div class="controls">  
                <button type="submit" class="btn"><?php echo $submitText ?></button>
            </div>
        </div>           
    </fieldset>
</form>