
<form class="form-horizontal" method="post" action="<?php echo $this->url('home/action', array('action' => 'createSubjectForm')) ?>">
    <fieldset>
        <div class="control-group">
            <label class="control-label" for="inputEmail">Subject</label>
            <div class="controls">
                <input type="text" name ="sub_name" placeholder="subject name…">
            </div>
        </div>
        
        <div class="control-group">
            <label class="control-label" for="inputEmail">Category</label>
            <div class="controls">
                <select name="cat_id">
		 <?php foreach($category as $c) {
                            echo '<option value=' . $c->getCatId() . '>' . $c->getCatName(). '</option>';
			}
		 ?>
                </select>
            </div>
        </div>
        
        <div class="control-group">
            <label class="control-label" for="inputEmail"></label>
            <div class="controls">
                <button type="submit" class="btn">Submit</button>
            </div>
        </div>
    </fieldset>
</form>

