<form class="form-horizontal" method="post" action="<?php echo $this->url('home/action', array('action' => 'createCategory')) ?>">
    <fieldset>      
         <div class="control-group">
            <label class="control-label" for="inputEmail">Category</label>
            <div class="controls">  
                <input type="text" name ="cat_name" placeholder="category name…"> <br />
            </div>
        </div>
            
        <div class="control-group">
            <label class="control-label" for="inputEmail"></label>
            <div class="controls">  
                <button type="submit" class="btn">Submit</button>
            </div>
        </div>
    </fieldset>
</form>
